# Site
repository: pxlwrx/jj-cv
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Johanna Schuleit
title: Communication Officer @Dachstiftung Diakonie
email: Johanna.Schuleit@t-online.de
# email_title: Email (Email title override)
# phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
website: johanna-schuleit.de
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: never

# Social links
# twitter_username: jekyllrb
#github_username: s-oehding
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
linkedin_username: johanna-schuleit-813959142
xing_username: Johanna_Schuleit
# pinterest_username: jekyll
# youtube_username: jekyll
#orcid_username: 0000-0003-3511-7121
# googlescholar_username: D847cGsAAAAJ

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpeg
# about_content: | # this will include new lines to allow paragraphs
#   I'm a fullstack software engineer specializing in building and designing distributed services. Big passion for Devops culture and 'you build it you run it' methodology. I like to inspire other developers to not only develop but also own and maintain their projects. To think outside the box and not be afraid of what comes after the development phase. It doesn't just run on your machine and everyone should understand what happens after ;)
about_content: | # this will include new lines to allow paragraphs
  Equality is one of the central motives in my life. Communication my strength. With my work I seek to give a voice to those who are too often overlooked by society.

content:
  - title: Experience
    layout: timeline
    content:
      - layout: left
        title: Dachstiftung Diakonie
        sub_title: Communications Officer</br>
        caption:
        daterange: 06/2020 - present
        link: www.dachstiftung-diakonie.de
        quote: >
          The **Dachstiftung Diakonie** is a social welfare organization with 4,000 employees. Corporate communications supports the social mission through public relations, fundraising and digitization. The traineeship included work and training in all areas of internal and external communications.
        description: | # this will include new lines to allow paragraphs
          **Specialization as Communication Officer:** 
          - Sustainability and change communication
          - Cross-media communication
            - Managing social media channels, website and intranet 
            - Writing articles & press releases; creating print and online media 
          -Digitization & project management workshops

      - layout: left
        title: International Fund for Animal Welfare
        sub_title: Campaign Intern
        caption:
        daterange: 09/2018 - 12/2018
        link: www.ifaw.org
        quote: >
          The International Fund for Animal Welfare is a global animal welfare organization.
        description: | # this will include new lines to allow paragraphs
          **RESPONSIBILITIES:**<br>
          Research and documentation in preparation for political lobbying. Support in organizing public events and campaigns. Target group-oriented preparation and communication of subjects, relevant to animal and wildlife protection. Support of social media channels and content creation.

      - layout: left
        title: Volkswagen Group
        sub_title: Internship External Relations & Sustainability
        caption:
        daterange: 10/2015 - 03/2016
        link: www.volkswagen.de
        quote: >
          As part of Group Communications, the Political Department acts as an intermediary between the company, politics and civil society actors.
        description: | # this will include new lines to allow paragraphs
          **RESPONSIBILITIES:**<br>
          Editorial work on corporate publishing projects, supporting stakeholder management, CSR and sustainability communication in the form of events and projects.

      - layout: left
        title: Heinrich Böll Foundation Schleswig-Holstein
        sub_title: Project Science creates good
        caption:
        daterange: 04/2015 - 09/2015
        link: www.boell-sh.de
        quote:
        description: | # this will include new lines to allow paragraphs
          **RESPONSIBILITIES:**<br>
          Developing creative concepts, such as stakeholder and network analysis, to optimize public relations of the foundation.
  - title: Education
    layout: timeline
    content:
      - layout: top-left
        title: M.A.Public Economics, Law and Politics
        sub_title: Leuphana University Lüneburg
        caption:
        daterange: 10/2016 - 03/2020
        quote:
        description: | # this will include new lines to allow paragraphs
          **Specialization:**<br>
          Sustainability Policy, Civil Society, Development economics, labor market and social policy
      - layout: top-left
        title: B.A. Sociology & Politics
        sub_title: Christian-Albrechts-University Kiel
        caption:
        daterange: 10/2012 - 09/2016
        quote:
        description: | # this will include new lines to allow paragraphs
          **Specialization:**<br>
          Economic and Organizational Sociology, Elective Business Studies, Marketing & Journalism

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      <div class="row">
        <div class="col-xs-12 col-md-6 content">
          <p>
          When i'm not at work you can find me ideally on a road or gravel bike tour through nature, the further out the better :)
          If the tour then ends at a lake where I can swim, I'm happy all around.<br>
          </p>
        </div>
        <div class="col-xs-12 col-md-6">
          <img src="images/bike-jj.jpg" />
          </div>
      </div>
# Footer
footer_show_references: true
references_title: References on request

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag

exclude:
  [
    "Gemfile",
    "Gemfile.lock",
    "node_modules",
    "vendor/bundle/",
    "vendor/cache/",
    "vendor/gems/",
    "vendor/ruby/",
    "lib/",
    "scripts/",
    "docker-compose.yml",
  ]
